# Generated by Django 4.0.4 on 2022-10-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
