# Generated by Django 4.0.4 on 2022-11-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ello', '0003_user_gender_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
